export const APPLICATION_ACTION_TYPE = {
  LOAD_STATE: 'LOAD_STATE',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  CLEAR_ALL: 'CLEAR_ALL',
  SET_CURRENT_FOLDER: 'SET_CURRENT_FOLDER',
  SET_LOG_IN: 'SET_LOG_IN',
};
