export const APPLICATION_ACTION_TYPE = {
  LOAD_STATE: "LOAD_STATE",
  SAVE_MEAL: "SAVE_MEAL",
  SAVE_DATA_GENERAL: "SAVE_DATA_GENERAL",
  SAVE_DOCUMENTS: "SAVE_DOCUMENTS",
  SAVE_CURRENT_SESSION: "SAVE_CURRENT_SESSION",
};
