export const API_URL_AUTH = {
  WEB_AUTH: 'v1/web/auth',
  WEB_USER: 'v1/web/user',
  AUTH: 'v1/auth',
  LOG_IN: 'login',
  USER: 'v1/user',
  PROFILE: 'profile',
  VIP_PACKAGE: 'v1/vip-package',
  TRIAL: 'trial',
  PURCHASE_IAP: 'purchase-iap',
  REMAINING_TOKEN: 'remaining-token-amount',
  RESTORE_IAP: 'restore-iap',
  CLEAR_DATA: 'clear-data',
  LOGIN_SOCIAL: 'login-social',
  SYNC_SOCIAL: 'sync-social',
  REFRESH_TOKEN: 'refresh-token',
};
export const API_URL = {
  GENERAL: 'v1/general',
  SEND_MAIL: 'send-mail',
  FEED_BACK: 'feedback',
  NOTES: 'v1/notes',
  WEB_NOTES: 'v1/web/notes',
  REPORT: 'report',
  FOLDER: 'v1/folders',
  BY_FOLDER: 'by-folder',
  FLASHCARD: 'flashcard',
  EXAM: 'exam',
  QUIZ: 'quiz',
  CHAT: 'chat',
  SUBMIT: 'submit',
  SCAN: 'scan',
  GOOGLE: 'google',
  WEB: 'web',
};
